/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_13;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo IP 330-14IKB
 */
public class Buat extends javax.swing.JFrame {

    private Log_In loginFrame;
    private LoginService loginService;

    /**
     * Creates new form Buat
     */
    public Buat(Log_In loginFrame, LoginService loginService) {
        initComponents();
        this.loginFrame = loginFrame;
        this.loginService = loginService;
        setLocationRelativeTo(null);
    }
    
        public Buat() {
        initComponents();
        this.loginService = new LoginService();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_Username_Daftar = new javax.swing.JTextField();
        tf_Password_Daftar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Buat = new javax.swing.JButton();
        Back_Daftar = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel1.setText("DAFTAR");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        btn_Buat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Buat.setText("Buat");
        btn_Buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuatActionPerformed(evt);
            }
        });

        Back_Daftar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Back_Daftar.setText("<");
        Back_Daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_DaftarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_Username_Daftar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_Password_Daftar)))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btn_Buat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Username_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Password_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(btn_Buat)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_DaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_DaftarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        if (loginFrame != null) {
            loginFrame.showLoginForm(); //Masih error
        } else {
            // Jika loginFrame null (dari testing), buka form login baru
            new Log_In().setVisible(true);
        }
    }//GEN-LAST:event_Back_DaftarMouseClicked

    private void btn_BuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuatActionPerformed
        // TODO add your handling code here:
        String username = tf_Username_Daftar.getText().trim();
        String password = tf_Password_Daftar.getText().trim();

        // Validasi input
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Username dan Password harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi panjang username/password (optional)
        if (username.length() < 3) {
            JOptionPane.showMessageDialog(this,
                    "Username harus minimal 3 karakter!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Coba buat user baru
        boolean createSuccess = loginService.createUser(username, password);

        if (createSuccess) {
            JOptionPane.showMessageDialog(this,
                    "Akun berhasil dibuat!\nUsername: " + username + "\nSilakan login dengan akun baru Anda.",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            // Kembali ke form login
            this.dispose();
            if (loginFrame != null) {
                loginFrame.showLoginForm(); //Ini juga masih error
            } else {
                // Jika loginFrame null (dari testing), buka form login baru
                new Log_In().setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Username '" + username + "' sudah digunakan!\nSilakan gunakan username lain.",
                    "Gagal Buat Akun",
                    JOptionPane.ERROR_MESSAGE);

            // Clear username field dan focus
            tf_Username_Daftar.setText("");
            tf_Username_Daftar.requestFocus();
        }
    }//GEN-LAST:event_btn_BuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat().setVisible(true); // Dan Error ketiga disini
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Back_Daftar;
    private javax.swing.JButton btn_Buat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_Password_Daftar;
    private javax.swing.JTextField tf_Username_Daftar;
    // End of variables declaration//GEN-END:variables
}
