/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_13;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo IP 330-14IKB
 */
public class Ubah extends javax.swing.JFrame {

    private Log_In loginFrame;
    private LoginService loginService;
    private String currentUsername;

    /**
     * Creates new form Ubah
     */
    public Ubah(Log_In loginFrame, LoginService loginService) {
        initComponents();
        this.loginFrame = loginFrame;
        this.loginService = loginService;
        setLocationRelativeTo(null);

        tf_Password_Ubah.setEnabled(false);
        btn_Ubah.setEnabled(false);
    }
    
        // Constructor untuk testing standalone
    public Ubah() {
        initComponents();
        this.loginService = new LoginService();
        setLocationRelativeTo(null);
        
        // Non-aktifkan field password dan tombol ubah sampai username ditemukan
        tf_Password_Ubah.setEnabled(false);
        btn_Ubah.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_Username_Ubah = new javax.swing.JTextField();
        tf_Password_Ubah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Cari = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        Back_Ubah = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel1.setText("UBAH");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        btn_Cari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Cari.setText("CARI");
        btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CariActionPerformed(evt);
            }
        });

        btn_Ubah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Ubah.setText("UBAH");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        Back_Ubah.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Back_Ubah.setText("<");
        Back_Ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_UbahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_Username_Ubah, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tf_Password_Ubah)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ubah)
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Cari)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Username_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btn_Cari))
                        .addGap(26, 26, 26)
                        .addComponent(tf_Password_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(btn_Ubah)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_UbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_UbahMouseClicked
        // TODO add your handling code here:
        this.dispose();
        loginFrame.showLoginForm();
    }//GEN-LAST:event_Back_UbahMouseClicked

    private void btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CariActionPerformed
        // TODO add your handling code here:
        String username = tf_Username_Ubah.getText().trim();

        // Validasi input
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Username harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Cari user di database
        Login user = loginService.findUserByUsername(username);

        if (user != null) {
            // Username ditemukan
            currentUsername = username; // Simpan username yang ditemukan
            JOptionPane.showMessageDialog(this,
                    "Username '" + username + "' ditemukan!\nSilakan masukkan password baru.",
                    "Username Ditemukan",
                    JOptionPane.INFORMATION_MESSAGE);

            // Aktifkan field password dan tombol ubah
            tf_Password_Ubah.setEnabled(true);
            btn_Ubah.setEnabled(true);

            // Focus ke field password
            tf_Password_Ubah.requestFocus();

        } else {
            // Username tidak ditemukan
            JOptionPane.showMessageDialog(this,
                    "Username '" + username + "' tidak ditemukan!\nSilakan buat akun terlebih dahulu.",
                    "Username Tidak Ditemukan",
                    JOptionPane.ERROR_MESSAGE);

            // Reset form
            tf_Username_Ubah.setText("");
            tf_Password_Ubah.setText("");
            tf_Password_Ubah.setEnabled(false);
            btn_Ubah.setEnabled(false);
            tf_Username_Ubah.requestFocus();
        }
    }//GEN-LAST:event_btn_CariActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
                String newPassword = tf_Password_Ubah.getText().trim();

        // Validasi input
        if (newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Password baru harus diisi!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update password
        boolean updateSuccess = loginService.updatePassword(currentUsername, newPassword);
        
        if (updateSuccess) {
            JOptionPane.showMessageDialog(this, 
                "Password berhasil diubah!\nSilakan login dengan password baru.", 
                "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Kembali ke form login
            this.dispose();
            loginFrame.showLoginForm();
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "Gagal mengubah password!\nSilakan coba lagi.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_UbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ubah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Back_Ubah;
    private javax.swing.JButton btn_Cari;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf_Password_Ubah;
    private javax.swing.JTextField tf_Username_Ubah;
    // End of variables declaration//GEN-END:variables
}
